### PR TITLE
adding sd-clevis

### PR DESCRIPTION
**Pull request by marcusweinhold**
this hook provides unlocking functionality for LUKS encrypted root volumes via a tang server or tpm2

### CODE REVIEW

**Comment by wolegis** [comment]
Thank you very much for your contribution. From my current, superficial understanding I think it is well worth to be included.

However, I first have to familiarize myself with the topic to be able to do a serious review.

From a first glance I have already spotted a few issues:

* Why include the busybox section more or less copied from *sd-tinyssh* or *sd-dropbox*?
* Do we really need all those `add_binary` statements? Some are already covered by busybox (`grep`, `sed`, probably also `bash`). The rest introduces additional dependencies. E.g., you cannot expect that `jose` or even `curl` are present in every Arch Linux installation.
* Better replace the section dealing with the TPM2 libraries with `add_full_dir` . If this is not possible at least use a `local` variable instead of  `_LIBRARY`.
* The last sentence in the help text is probably not correct. Install hooks for systemd based initramfs are mainly copying stuff. They do not imply any order of execution when the initramfs system is started. This is exclusively achieved by dependency statements in systemd unit files. (There are cases of install hooks that have to be specified before others because the first ones do some kind of preparation the others do depend on. Most prominently `autodetect` and `systemd`.)

**Comment by marcusweinhold** [comment]
Hi @wolegis,

thanks for your feedback!

> Why include the busybox section more or less copied from sd-tinyssh or sd-dropbox?
Do we really need all those add_binary statements? Some are already covered by busybox (grep, sed, probably also bash)

Clevis is basically a collection of bash scripts relying on the shell standard tools, hence the busybox section.
* `sed` is indeed not required and removed in my latest commit
* `bash` and `tr` are not provided by `busybox`:
  ```bash
  ~ % /usr/lib/initcpio/busybox --list | grep -e '^true$' -e bash | wc -l
  0
  ```
* while `grep` is provided by `busybox`, it does not implement the `-B` flag [required by clevis](https://github.com/latchset/clevis/blob/master/src/luks/clevis-luks-common-functions.in#L109). So unlocking fails, if non-busybox `grep` is not added
  ```bash
  ~ % /usr/lib/initcpio/busybox grep --help 
  BusyBox v1.36.1 () multi-call binary.
  
  Usage: grep [-HhnlLoqvsrRiwFE] [-m N] { PATTERN | -e PATTERN... | -f FILE... } [FILE]...
  
  Search for PATTERN in FILEs (or stdin)
  
          -H      Add 'filename:' prefix
          -h      Do not add 'filename:' prefix
          -n      Add 'line_no:' prefix
          -l      Show only names of files that match
          -L      Show only names of files that don't match
          -c      Show only count of matching lines
          -o      Show only the matching part of line
          -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
          -v      Select non-matching lines
          -s      Suppress open and read errors
          -r      Recurse
          -R      Recurse and dereference symlinks
          -i      Ignore case
          -w      Match whole words only
          -x      Match whole lines only
          -F      PATTERN is a literal (not regexp)
          -E      PATTERN is an extended regexp
          -m N    Match up to N times per file
          -e PTRN Pattern to match
          -f FILE Read pattern from file
  ```

> The rest introduces additional dependencies. E.g., you cannot expect that jose or even curl are present in every Arch Linux installation.

`curl`, `jose` and `cryptsetup` are [dependencies of clevis](https://archlinux.org/packages/extra/x86_64/clevis/), so I did not add them in the `PKGBUILD`. If you prefer them being listed as optional deps, I'm happy to do so. On the other hand, `tpm2-tools` is also an optional dependency of `clevis` and consequently could be removed. Tell me, what you prefer.

> Better replace the section dealing with the TPM2 libraries with add_full_dir . If this is not possible at least use a local variable instead of _LIBRARY.

`add_full_dir` would add `/usr/lib`, overkill :) We only need libtss2.tcti-device.so.0.0.0 and the symlinks to it. I have updated it, to use a `local` var, as you suggested

> The last sentence in the help text is probably not correct.

Indeed, you are correct. There is the aforementioned `grep -B` problem though: `sd-dropbear` and `sd-tinyssh` would replace the `grep` binary with a symlink to `busybox` again. I have updated the help string to accordingly.

---

I have further changed the clevis binary section to include only the required scripts. Encryption tools are not required in an initrd.

**Comment by wolegis** [comment]
Thanks for the updates. Definitely going into the right direction.

Some further comments:

**Dependencies**

In general, this package is by its nature a collection of pieces that users can pick to their liking. Consequently, it is no option to define hard dependencies, just because one or another piece requires something. That's why the install scripts sometimes resort to testing on the presence of a certain package - as you do with package *clevis*.

I didn't have a look on the dependencies of package *clevis* before writing my previous comment. Now I have learned that we can safely expect `jose` and `bash` to be present. (`bash`  is actually pulled in by `base`.) `curl` is another topic. It's just an optional dependency of `clevis`. So either we test on the presence of `curl` before copying or (preferrable, but probably not doable) avoid the dependency on `curl`. (The scripts are a PITA to wrap my head around. Give me some time.)

`grep` is pulled in by `base`, so can be expected to be present in any case. I don't like the significance of ordering of install hooks introduced by `grep` - but have no solution right now.

**add_full_dir**

The mkinitcpio function `add_full_dir` has a filter feature. See [mkinitcpio(8)](https://man.archlinux.org/man/mkinitcpio.8.en#ABOUT_INSTALL_HOOKS) for details. Maybe that is helpful when copying the libtss2 libs.

**Comment by marcusweinhold** [comment]
>  add_full_dir

Thanks for reminding me to rtfm once in a while :) looks much better with `add_full_dir`.

> Dependencies

I have removed the opt dep to `tpm2-tools` in `PKGBUILD`, since it's referenced in `clevis` already.

The hook does now check for both `tpm2-tools` and `curl`. If neither is found, it will throw an error and do nothing. If either or both are found, it will add the respective files.

**Comment by wolegis** [comment]
I did forget about this PR, but was busy with other things lately. Now is vacation time. So please bear with me.

**Pull request merged**
